mixed-port: 7890
redir-port: 7892
authentication: [""]
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: :9999
external-ui: ui
secret: 
tun: {enable: false}
experimental: {ignore-resolve-fail: true, interface-name: en0}
dns: {enable: true, ipv6: false, listen: 0.0.0.0:1053, use-hosts: true, enhanced-mode: redir-host, default-nameserver: [114.114.114.114, 223.5.5.5, 127.0.0.1:53], nameserver: [114.114.114.114, 223.5.5.5], fallback: [1.0.0.1, 8.8.4.4], fallback-filter: {geoip: true}}
store-selected: true
proxies:
  - {name: ğŸ‡°ğŸ‡· é¦–å°”_ARM, server: arm.rastyu.ml, port: 443, type: trojan, password: a2a8ff45-046c-4809-906f-797481ce520d, sni: arm.rastyu.ml, skip-cert-verify: true, udp: true}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM, server: xin.rastyu.tk, port: 443, type: trojan, password: ff1ae45d-a0a1-4b2a-a41f-d426744359a2, sni: xin.rastyu.tk, skip-cert-verify: true, udp: true}
  - {name: ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ, server: test.rastyu.ml, port: 443, type: trojan, password: e5a7ad01-3864-4228-9e8e-139d12938212, sni: test.rastyu.ml, skip-cert-verify: true, udp: true}
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - DIRECT
  - name: ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
    type: select
    proxies:
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - DIRECT
  - name: ğŸ“  ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¶ TikTok
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ° è¿ªå£«å°¼+
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ“º æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¬ EMBYå…¬ç›Š
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸ“‹ DIYåå•
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸ¿ å¥ˆé£è§†é¢‘
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¥ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ›ï¸ é•¿åŸç½‘ç»œ
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ›¡ï¸ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ³ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - DIRECT
      - ğŸ‡°ğŸ‡· é¦–å°”_ARM
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ_ARM
      - ğŸ‡°ğŸ‡· é¦–å°”_å¤‡èƒ
      - ğŸ”° æ‰‹åŠ¨åˆ‡æ¢
rules:
 - DOMAIN-KEYWORD,tiktokcdn,ğŸ¶ TikTok
 - DOMAIN-SUFFIX,emby.wtf,ğŸ¬ EMBYå…¬ç›Š
 - DOMAIN-SUFFIX,jmsooo.com,ğŸ¬ EMBYå…¬ç›Š
 - DOMAIN-SUFFIX,fanart.tv,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,tmdb.org,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,themoviedb.org,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,keeflys.com,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,aptoide.com,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,fast.com,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,speedtest.net,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,ooklaserver.net,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,speed.cloudflare.com,ğŸ“‹ DIYåå•
 - DOMAIN-SUFFIX,git.io,ğŸ›ï¸ é•¿åŸç½‘ç»œ
 - DOMAIN,update.synology.com,ğŸ›¡ï¸ åº”ç”¨å‡€åŒ–
 - DOMAIN,update7.synology.com,ğŸ›¡ï¸ åº”ç”¨å‡€åŒ–
 - DOMAIN,autoupdate7.synology.com,ğŸ›¡ï¸ åº”ç”¨å‡€åŒ–
 - DOMAIN,autoupdate7.synology.cn,ğŸ›¡ï¸ åº”ç”¨å‡€åŒ–
 - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
 - MATCH,ğŸ³ æ¼ç½‘ä¹‹é±¼
